### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by schaperk** [ringcentral/ringcentral-c2d#11]
I am having compile issues when using the component.

Here's what happened.

1) I did a "yarn add ringcentral-c2d" -  but then I get an error saying I needed to install to do "yarn add node-sass"
2) after than I am now receiving this issue:

/node_modules/ringcentral-c2d/lib/RingCentralC2DWidget/styles.scss (./node_modules/css-loader/dist/cjs.js??ref--6-oneOf-5-1!./node_modules/postcss-loader/src??postcss!./node_modules/resolve-url-loader??ref--6-oneOf-5-3!./node_modules/sass-loader/dist/cjs.js??ref--6-oneOf-5-4!./node_modules/ringcentral-c2d/lib/RingCentralC2DWidget/styles.scss)
SassError: File to import not found or unreadable: theme.
        on line 1 of /Users/schaper/dev/vetspire/web/node_modules/ringcentral-c2d/lib/RingCentralC2DWidget/styles.scss
>> @import 'theme';

   ^

**Comment by embbnux** [comment]
Hi @schaperk , thanks for feedback. I think there are something wrong in release CI. Will check this.

**Comment by embbnux** [comment]
Hi @schaperk, just checked. It is caused by webpack config required:

```js
// Add following into webpack config.module.rules
{
  test: /\.sass|\.scss/,
  use: [
    {
      loader: 'style-loader',
    },
    {
      loader: 'css-loader',
      options: {
        modules: {
          localIdentName: `[path]_[name]_[local]_[hash:base64:5]`,
        },
      },
    },
    {
      loader: 'sass-loader',
      options: {
        sassOptions: {
          includePaths: [path.resolve(__dirname, 'node_modules/ringcentral-c2d/lib/themes')],
          outputStyle: 'extended'
        }
      },
    },
  ],
},
```
I will update it into docs, thanks so much

**Comment by embbnux** [comment]
Closed by inactive
