### ISSUE TITLE
C2D is not displayed for <input type="text" tags

### ISSUE THREAD

**Issue by GregRG-Dev** [ringcentral/ringcentral-c2d#41]
If you hover over an input element the c2d is not displayed.

Tried with chrome : Version 120.0.6099.130 (Official Build) (64-bit) and Edge : Version 120.0.2210.91 (Official build) (64-bit)
on the demo webpage (https://ringcentral.github.io/ringcentral-c2d/) and on a custom test page for business connect.

**Comment by embbnux** [comment]
Hi @GregRG-Dev Thanks for reporting this. I can also reproduce it. 
After checking, It is by design now. The input element is disabled for display c2d from v1.0.0.  
Can you share more details/reason why you want to get it displayed for user input?

**Comment by GregRG-Dev** [comment]
I'll close the issue, we added our own way of dealing with that.
